### ISSUE TITLE
example1.py ssl_context error

### ISSUE THREAD

**Issue by sepulworld** [tomplus/kubernetes_asyncio#87]
Hi! I'm testing out this library and ran into an error with example1.py

Python3

pip list
```
$ pip list
Package             Version
------------------- ----------
aiofiles            0.4.0
aiohttp             4.0.0a1
aniso8601           6.0.0
apispec             3.2.0
apistar             0.7.2
appnope             0.1.0
astroid             2.3.3
async-timeout       3.0.1
attrs               19.3.0
backcall            0.1.0
cachetools          4.0.0
certifi             2019.11.28
chardet             3.0.4
Click               7.0
decorator           4.4.1
dnspython           1.16.0
docopt              0.6.2
google-auth         1.10.0
graphene            2.1.7
graphql-core        2.2
graphql-relay       2.0.0
graphql-server-core 1.1.1
h11                 0.9.0
httptools           0.0.13
idna                2.8
ipython             7.11.0
ipython-genutils    0.2.0
isort               4.3.21
itsdangerous        1.1.0
jedi                0.15.2
Jinja2              2.10.3
kubernetes          10.0.1
kubernetes-asyncio  10.0.1
lazy-object-proxy   1.4.3
MarkupSafe          1.1.1
marshmallow         3.3.0
mccabe              0.6.1
more-itertools      8.0.2
multidict           4.7.2
oauthlib            3.1.0
packaging           19.2
parse               1.14.0
parso               0.5.2
pexpect             4.7.0
pickleshare         0.7.5
pip                 19.3.1
pluggy              0.13.1
prometheus-client   0.7.1
promise             2.3
prompt-toolkit      3.0.2
ptyprocess          0.6.0
py                  1.8.1
pyasn1              0.4.8
pyasn1-modules      0.2.7
Pygments            2.5.2
pylint              2.4.4
pyparsing           2.4.6
pytest              5.3.2
python-dateutil     2.8.1
python-multipart    0.0.5
PyYAML              5.3b1
redis               3.2.1
requests            2.22.0
requests-oauthlib   1.3.0
requests-toolbelt   0.9.1
responder           1.3.1
rfc3986             1.3.2
rsa                 4.0
Rx                  3.0.1
setuptools          42.0.2
six                 1.13.0
starlette           0.10.7
traitlets           4.3.3
typesystem          0.2.4
typing-extensions   3.7.4.1
urllib3             1.25.7
uvicorn             0.11.1
uvloop              0.14.0
wcwidth             0.1.7
websocket-client    0.57.0
websockets          8.1
wheel               0.33.6
whitenoise          5.0.1
wrapt               1.11.2
yarl                1.4.2
```

K8s client / server
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T14:25:20Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.5", GitCommit:"20c265fef0741dd71a66480e35bd69f18351daea", GitTreeState:"clean", BuildDate:"2019-10-15T19:07:57Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```

python example/example1.py
```
Traceback (most recent call last):
  File "1.py", line 22, in <module>
    loop.run_until_complete(main())
  File "/Users/zane/.pyenv/versions/3.8.0/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "1.py", line 12, in main
    v1 = client.CoreV1Api()
  File "/Users/zane/.local/share/virtualenvs/dinghy-ping-ePAjWOtt/lib/python3.8/site-packages/kubernetes_asyncio/client/api/core_v1_api.py", line 32, in __init__
    api_client = ApiClient()
  File "/Users/zane/.local/share/virtualenvs/dinghy-ping-ePAjWOtt/lib/python3.8/site-packages/kubernetes_asyncio/client/api_client.py", line 72, in __init__
    self.rest_client = rest.RESTClientObject(configuration)
  File "/Users/zane/.local/share/virtualenvs/dinghy-ping-ePAjWOtt/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 67, in __init__
    connector = aiohttp.TCPConnector(
TypeError: __init__() got an unexpected keyword argument 'ssl_context'
Exception ignored in: <function RESTClientObject.__del__ at 0x10e5d4430>
Traceback (most recent call last):
  File "/Users/zane/.local/share/virtualenvs/dinghy-ping-ePAjWOtt/lib/python3.8/site-packages/kubernetes_asyncio/client/rest.py", line 84, in __del__
AttributeError: 'RESTClientObject' object has no attribute 'pool_manager'
```

Running a non asyncio example script with python-client library works fine
```
$ cat non-async-example.py
from kubernetes import client, config

# Configs can be set in Configuration class directly or using helper utility
config.load_kube_config()

v1 = client.CoreV1Api()
print("Listing pods with their IPs:")
ret = v1.list_pod_for_all_namespaces(watch=False)
for i in ret.items:
    print("%s\t%s\t%s" % (i.status.pod_ip, i.metadata.namespace, i.metadata.name))
```

Curious, if something stands out as an issue here.

**Comment by sepulworld** [comment]
I think I found the issue, still testing though. my install aiohttp is too new and ssl_context has been removed as an initializer variable.

**Comment by sepulworld** [comment]
Yep, example works fine with aiohttp 3.6.2

https://github.com/aio-libs/aiohttp/releases - looks like they have a new alpha release live with depreciated inputs removed

**Comment by tomplus** [comment]
Thanks for your investigation. I'll add a condition to the `requriements.txt` to avoid version >=4 for a while and fix it when a stable version appears.

**Comment by sepulworld** [comment]
> Thanks for your investigation. I'll add a condition to the `requriements.txt` to avoid version >=4 for a while and fix it when a stable version appears.

Sounds good! I put in the PR for the requirements.txt update for you.
